language: cpp
dist: bionic
compiler:
  - gcc
  - clang 

install: 
  # Required on bionic
  - sudo apt update -qq
  # Qt5
  - sudo apt install -qq qt5-qmake qt5-default
  # clang-tidy
  - apt-cache search clang-tidy
  - sudo apt-get install -qq clang clang-tidy

script: 
  # Build and run this project
  - qmake
  - make debug
  - ./travis_qmake_gcc_cpp14_clang-tidy
  # clang-tidy
  - ./do_clang-tidy
